# Generated by Django 3.1.2 on 2020-11-28 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('externalId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
                ('retweets', models.IntegerField()),
                ('favorites', models.IntegerField()),
                ('tweetHtml', models.TextField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StockChart',
            fields=[
                ('chartHtml', models.TextField()),
                ('maxSwing', models.FloatField()),
                ('tweetId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EMIOTS203.tweet')),
            ],
        ),
    ]
