# Generated by Django 3.1.2 on 2020-11-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetAndStockChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweetHtmlContent', models.TextField()),
                ('charttHtmlContent', models.TextField()),
                ('maxStockChange', models.FloatField()),
                ('publish_date', models.DateTimeField()),
            ],
        ),
    ]
