# Generated by Django 3.1.2 on 2020-11-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMIOTS203', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetandstockchart',
            old_name='charttHtmlContent',
            new_name='chartHtmlContent',
        ),
    ]
