# Generated by Django 3.1.2 on 2020-11-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMIOTS203', '0002_auto_20201121_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweetandstockchart',
            options={'ordering': ['-publish_date']},
        ),
    ]
